# Generated by Django 2.0.5 on 2018-05-28 10:49

import board.models.items
import board.models.team
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.ForeignKey(default=board.models.items.ItemStatus.get_default_item_status, on_delete=django.db.models.deletion.SET_DEFAULT, to='board.ItemStatus'),
        ),
        migrations.AlterField(
            model_name='membershipinfo',
            name='role',
            field=models.ForeignKey(default=board.models.team.UserRole.get_default_role, on_delete=django.db.models.deletion.SET_DEFAULT, to='board.UserRole'),
        ),
    ]
