# Generated by Django 2.0.5 on 2018-05-29 17:54

import board.models.items
import board.models.team
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_start_date', models.DateTimeField()),
                ('sprint_duration', models.IntegerField()),
                ('discussion_period', models.IntegerField()),
                ('icon', models.URLField(blank=True, null=True, verbose_name='Link to board avatar image')),
            ],
        ),
        migrations.CreateModel(
            name='ColumnTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_templates', to='board.BoardSettings')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='board.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.ForeignKey(default=board.models.items.ItemStatus.get_default_item_status, on_delete=django.db.models.deletion.SET_DEFAULT, to='board.ItemStatus'),
        ),
        migrations.AlterField(
            model_name='membershipinfo',
            name='role',
            field=models.ForeignKey(default=board.models.team.UserRole.get_default_role, on_delete=django.db.models.deletion.SET_DEFAULT, to='board.UserRole'),
        ),
        migrations.AddField(
            model_name='board',
            name='settings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.BoardSettings'),
        ),
    ]
