# Generated by Django 2.0.5 on 2018-05-29 19:32

from board.models import ColumnTemplate
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20180529_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='name',
            field=models.CharField(default='name', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='columntemplate',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_names', to='board.BoardSettings'),
        ),
    ]
