# Generated by Django 2.0.5 on 2018-05-27 20:39

import board.models.board
import board.models.team
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20180527_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='settings',
            field=models.OneToOneField(default=board.models.BoardSettings.get_default_settings, on_delete=django.db.models.deletion.SET_DEFAULT, to='board.BoardSettings'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.ForeignKey(default=board.models.ItemStatus.get_default_item_status, on_delete=django.db.models.deletion.SET_DEFAULT, to='board.ItemStatus'),
        ),
        migrations.AlterField(
            model_name='membershipinfo',
            name='role',
            field=models.ForeignKey(default=board.models.team.UserRole.get_default_role, on_delete=django.db.models.deletion.SET_DEFAULT, to='board.UserRole'),
        ),
    ]
