# Generated by Django 2.0.5 on 2018-05-30 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_board_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='duration',
        ),
    ]
