# Generated by Django 2.0.5 on 2018-05-28 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20180527_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now=True, verbose_name='Start date')),
                ('duration', models.DurationField(verbose_name='Duration')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='status',
            field=models.CharField(choices=[('n', 'New'), ('d', 'Discussion'), ('r', 'Running'), ('c', 'Closed')], default='n', max_length=2, verbose_name='Board status - new, running or discussion period'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='board.Board'),
        ),
        migrations.AddField(
            model_name='board',
            name='current_sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_where_is_current', to='board.Sprint'),
        ),
        migrations.AddField(
            model_name='board',
            name='previous_sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_where_is_previous', to='board.Sprint'),
        ),
    ]
