# Generated by Django 2.0.5 on 2018-05-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_remove_sprint_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='duration',
            field=models.IntegerField(default=14, verbose_name='Duration in days'),
            preserve_default=False,
        ),
    ]
