# Generated by Django 2.0.5 on 2018-05-28 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20180528_0820'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupAssignee',
        ),
        migrations.DeleteModel(
            name='UserProfileAssignee',
        ),
    ]
