# Generated by Django 2.0.5 on 2018-05-30 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_sprint_duration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('item', 'profile')},
        ),
    ]
