# Generated by Django 2.0.5 on 2018-05-28 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20180528_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_templates', to='board.BoardSettings')),
            ],
        ),
        migrations.RemoveField(
            model_name='column',
            name='board',
        ),
        migrations.AddField(
            model_name='column',
            name='sprint',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='board.Sprint'),
            preserve_default=False,
        ),
    ]
