# Generated by Django 2.0.5 on 2018-05-28 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20180528_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='settings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.BoardSettings'),
        ),
    ]
